name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup do Node JS
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18.2.0
        
